Repository getporter/porter, pull requests merged in 2019-03, with the labels that each got.

#146 Add porter schema root command
  CONTRIBUTING.md
  cmd/porter/main.go
  cmd/porter/run.go
  cmd/porter/schema.go
  pkg/config/actions.go
  pkg/config/actions_test.go
  pkg/config/config.go
  pkg/config/helpers.go
  pkg/exec/exec.go
  pkg/mixin/exec/main_test.go
  pkg/mixin/metadata.go
  pkg/mixin/provider/filesystem.go
  pkg/mixin/provider/filesystem_test.go
  pkg/mixin/runner.go
  pkg/porter/helpers.go
  pkg/porter/main_test.go
  pkg/porter/mixins.go
  pkg/porter/mixins_test.go
  pkg/porter/porter.go
  pkg/porter/schema.go
  pkg/porter/schema/manifest.json
  pkg/porter/schema_test.go
  pkg/porter/testdata/schema.json
Labels: review

#197 Search waffle board for good first issues
  CONTRIBUTING.md
Labels: review

#204 Update docs with new logo
  README.md
  docs/resources/_gen/assets/scss/sass/styles.scss_b95b077eb505d5c0aff8055eaced30ad.content
  docs/static/images/porter-logo.png
  docs/static/images/porter-notext.png
  docs/static/images/porter-text.png
  docs/themes/porter/layouts/index.html
  docs/themes/porter/layouts/partials/sidebar.html
  docs/themes/porter/static/src/sass/helm-home.scss
Labels: review

#208 Explain when to log to stderr
  CONTRIBUTING.md
  docs/resources/_gen/assets/scss/sass/styles.scss_b95b077eb505d5c0aff8055eaced30ad.content
Labels: review

#206 Swap out logo on our favicon
  .gitignore
  docs/themes/porter/layouts/index.html
  docs/themes/porter/layouts/partials/header.html
  docs/themes/porter/static/src/img/favicon-152.png
  docs/themes/porter/static/src/img/favicon.ico
  docs/themes/porter/static/src/img/favicon.png
Labels: review

#203 Remove hard-coded helm styles.min.css from repo
  docs/themes/porter/layouts/partials/header.html
  docs/themes/porter/static/src/css/styles.min.css
  docs/themes/porter/static/src/css/styles.min.css.map
Labels: review

#205 Adding design document for kubernetes mixin
  docs/content/design/kubernetes-mixin.md
Labels: review

#211 Complete the exec schema command
  pkg/config/actions.go
  pkg/exec/schema/exec.json
  pkg/exec/testdata/schema.json
  pkg/porter/schema.go
  pkg/porter/schema_test.go
  pkg/porter/testdata/schema.json
Labels: review

#213 Remove extra call to packr2 build
  mixin.mk
Labels: meta, review

#214 Move templates from config to porter package
  cmd/porter/run_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/porter/build_test.go
  pkg/porter/create.go
  pkg/porter/porter.go
  pkg/porter/schema.go
  pkg/porter/templates.go
  pkg/porter/templates/porter.yaml
  pkg/porter/templates/run
  pkg/porter/templates/schema.json
  pkg/porter/templates_test.go
Labels: review

#217 Require generate for the runtime target
  Makefile
Labels: review

#212 Include all supported actions in the schema
  Gopkg.lock
  Gopkg.toml
  pkg/exec/schema/exec.json
  pkg/exec/testdata/schema.json
  pkg/porter/schema.go
  pkg/porter/schema_test.go
  pkg/porter/templates/schema.json
  pkg/porter/testdata/porter.yaml
  pkg/porter/testdata/schema.json
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonpointer/pointer.go
  vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonreference/reference.go
  vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonschema/draft.go
  vendor/github.com/xeipuuv/gojsonschema/errors.go
  vendor/github.com/xeipuuv/gojsonschema/format_checkers.go
  vendor/github.com/xeipuuv/gojsonschema/internalLog.go
  vendor/github.com/xeipuuv/gojsonschema/jsonContext.go
  vendor/github.com/xeipuuv/gojsonschema/jsonLoader.go
  vendor/github.com/xeipuuv/gojsonschema/locales.go
  vendor/github.com/xeipuuv/gojsonschema/result.go
  vendor/github.com/xeipuuv/gojsonschema/schema.go
  vendor/github.com/xeipuuv/gojsonschema/schemaLoader.go
  vendor/github.com/xeipuuv/gojsonschema/schemaPool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaReferencePool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaType.go
  vendor/github.com/xeipuuv/gojsonschema/subSchema.go
  vendor/github.com/xeipuuv/gojsonschema/types.go
  vendor/github.com/xeipuuv/gojsonschema/utils.go
  vendor/github.com/xeipuuv/gojsonschema/validation.go
Labels: review

#219 Fix canary install
  Makefile
  mixin.mk
  scripts/install/install-linux.sh
  scripts/install/install-mac.sh
  scripts/install/install-windows.ps1
Labels: review

#220 Wrap steps in the containing action
  cmd/exec/main.go
  pkg/exec/exec.go
  pkg/exec/exec_test.go
  pkg/exec/install.go
  pkg/exec/install_test.go
  pkg/exec/testdata/exec_input.yaml
  pkg/mixin/runner.go
  pkg/mixin/testdata/exec_input.yaml
  pkg/porter/build.go
  pkg/porter/run.go
  pkg/porter/run_test.go
Labels: review

#222 Publish our roadmap
  README.md
Labels: review

#227 Suppress mkdir 'directory exists' output in Windows install
  scripts/install/install-windows.ps1
Labels: review

#210 ref(ci): add brigade
  Makefile
  brigade.js
  mixin.mk
Labels: enhancement, review

#230 chore(ci): remove azure-pipelines.yaml
  azure-pipelines.yml
Labels: review

#228 Adding THE KUBERNETES MIXIN
  Makefile
  cmd/kubernetes/build.go
  cmd/kubernetes/install.go
  cmd/kubernetes/main.go
  cmd/kubernetes/schema.go
  cmd/kubernetes/uninstall.go
  cmd/kubernetes/upgrade.go
  cmd/kubernetes/version.go
  docs/content/design/kubernetes-mixin.md
  pkg/kubernetes/build.go
  pkg/kubernetes/helpers.go
  pkg/kubernetes/install.go
  pkg/kubernetes/install_test.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/schema.go
  pkg/kubernetes/schema/kubernetes.json
  pkg/kubernetes/schema_test.go
  pkg/kubernetes/step.go
  pkg/kubernetes/testdata/install-input-bad-outputs.yaml
  pkg/kubernetes/testdata/install-input-bad-wait-flag.yaml
  pkg/kubernetes/testdata/install-input-no-manifests.yaml
  pkg/kubernetes/testdata/install-input.yaml
  pkg/kubernetes/testdata/schema.json
  pkg/kubernetes/testdata/uninstall-input.yaml
  pkg/kubernetes/testdata/upgrade-input.yaml
  pkg/kubernetes/uninstall.go
  pkg/kubernetes/uninstall_test.go
  pkg/kubernetes/upgrade.go
  pkg/kubernetes/upgrade_test.go
  pkg/kubernetes/version.go
Labels: review

#221 Document how to implement mixin commands
  docs/config.toml
  docs/content/mixin-commands.md
  docs/resources/_gen/assets/scss/sass/styles.scss_b95b077eb505d5c0aff8055eaced30ad.content
Labels: review

#234 Re-enable azure pipelines
  azure-pipelines.yml
Labels: review

#229 Add porter install command
  cmd/porter/bundle.go
  cmd/porter/bundle_test.go
  cmd/porter/main.go
  cmd/porter/main_test.go
  pkg/parameters/parameters.go
  pkg/parameters/parameters_test.go
  pkg/porter/install.go
  pkg/porter/install_test.go
Labels: review

#236 chore(brigade.js): update Kashti build URL
  brigade.js
Labels: review

#238 Omit empty bundle fields
  pkg/config/manifest.go
  pkg/porter/bundle.go
Labels: review

#237 Inject porter-debug param into all bundles
  pkg/porter/build.go
  pkg/porter/build_test.go
Labels: review

#242 feat(.gitignore): ignore build relics in example bundle dirs
  .gitignore
Labels: review

#233 Install a bundle with duffle
  Gopkg.lock
  Makefile
  cmd/porter/bundle.go
  cmd/porter/bundle_test.go
  pkg/cnab/provider/bundle.go
  pkg/cnab/provider/claims.go
  pkg/cnab/provider/credentials.go
  pkg/cnab/provider/duffle.go
  pkg/cnab/provider/install.go
  pkg/cnab/provider/parameters.go
  pkg/porter/build.go
  pkg/porter/cnab.go
  pkg/porter/install.go
  pkg/porter/install_test.go
  pkg/porter/porter.go
  pkg/porter/testdata/install/base-params.txt
  pkg/porter/testdata/install/dev-params.txt
  scripts/test/test-cli.sh
  scripts/test/test-hello.sh
  scripts/test/test-wordpress.sh
  vendor/golang.org/x/crypto/cast5/cast5.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/armor/encode.go
  vendor/golang.org/x/crypto/openpgp/canonical_text.go
  vendor/golang.org/x/crypto/openpgp/clearsign/clearsign.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/openpgp/errors/errors.go
  vendor/golang.org/x/crypto/openpgp/keys.go
  vendor/golang.org/x/crypto/openpgp/packet/compressed.go
  vendor/golang.org/x/crypto/openpgp/packet/config.go
  vendor/golang.org/x/crypto/openpgp/packet/encrypted_key.go
  vendor/golang.org/x/crypto/openpgp/packet/literal.go
  vendor/golang.org/x/crypto/openpgp/packet/ocfb.go
  vendor/golang.org/x/crypto/openpgp/packet/one_pass_signature.go
  vendor/golang.org/x/crypto/openpgp/packet/opaque.go
  vendor/golang.org/x/crypto/openpgp/packet/packet.go
  vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/reader.go
  vendor/golang.org/x/crypto/openpgp/packet/signature.go
  vendor/golang.org/x/crypto/openpgp/packet/signature_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetric_key_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetrically_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/userattribute.go
  vendor/golang.org/x/crypto/openpgp/packet/userid.go
  vendor/golang.org/x/crypto/openpgp/read.go
  vendor/golang.org/x/crypto/openpgp/s2k/s2k.go
  vendor/golang.org/x/crypto/openpgp/write.go
Labels: review

#239 Default --debug to the porter-debug parameter at runtime
  cmd/porter/run.go
  pkg/config/config.go
  pkg/porter/run.go
  pkg/porter/run_test.go
Labels: review

#241 feat(examples): make mysql server name a required param
  examples/azure-mysql-wordpress/porter.yaml
Labels: review

#245 Add google analytics
  docs/themes/porter/layouts/index.html
  docs/themes/porter/layouts/partials/footer-blog.html
Labels: review

#244 Default the porter-debug flag using --debug
  cmd/porter/bundle.go
  pkg/porter/install.go
  pkg/porter/install_test.go
  scripts/test/test-hello.sh
  scripts/test/test-wordpress.sh
Labels: review
